networks:
  ipv6:
    driver: bridge
    ipam:
      config:
        - subnet: 2a05:b540:cadd::/64
    enable_ipv4: false
    enable_ipv6: true
  ipv4: 
    driver: bridge
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.255.0.0/16
services:
  # tcpdump-discovery:
  #   network_mode: host
  #   image: nicolaka/netshoot
  #   entrypoint:
  #     - tcpdump
  #     - -i 
  #     - any
  #     - -vvv
  #     - -ttt
  #     # neighbor solicitations
  #     - 'arp or (icmp6 and ip6[40] = 135)'

  tcpdump-net:
    network_mode: host
    image: nicolaka/netshoot
    entrypoint:
      - tcpdump
      - -i 
      - any
      - -nnvvvttt
      - 'net 64:ff9b:dead:beef::/96 or host 10.0.0.1 or host 2a05:b540:cadd::4'
  siit:
    build:
      context: .
      args:
        BASE_IMAGE: nicolaka/netshoot
    network_mode: host
    privileged: true
    user: root:root
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing 
    command:
    # - -host-ipv4=10.255.0.2
    # - -host-ipv6=2a05:b540:cadd::2
    - -pool=64:ff9b:dead:beef::/96
    - -ipv4=10.0.0.1
    # nginx
    - -ipv6=2a05:b540:cadd::4

  netcat:
    networks:
      ipv6:
        ipv6_address: 2a05:b540:cadd::4
    image: nicolaka/netshoot
    init: true
    tty: true
    command:
      - nc
      - -6vnlk
      - "80"

  nginx:
    networks:
      ipv6:
        ipv6_address: 2a05:b540:cadd::5
    image: nginx
