// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: siit/v1alpha1/siit.proto

package v1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/hown3d/siit-ebpf/pkg/apis/siit/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EAMTServiceName is the fully-qualified name of the EAMTService service.
	EAMTServiceName = "siit.v1alpha1.EAMTService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EAMTServiceListProcedure is the fully-qualified name of the EAMTService's List RPC.
	EAMTServiceListProcedure = "/siit.v1alpha1.EAMTService/List"
	// EAMTServiceCreateProcedure is the fully-qualified name of the EAMTService's Create RPC.
	EAMTServiceCreateProcedure = "/siit.v1alpha1.EAMTService/Create"
	// EAMTServiceDeleteProcedure is the fully-qualified name of the EAMTService's Delete RPC.
	EAMTServiceDeleteProcedure = "/siit.v1alpha1.EAMTService/Delete"
)

// EAMTServiceClient is a client for the siit.v1alpha1.EAMTService service.
type EAMTServiceClient interface {
	List(context.Context, *v1alpha1.ListRequest) (*v1alpha1.ListResponse, error)
	Create(context.Context, *v1alpha1.CreateRequest) (*v1alpha1.CreateResponse, error)
	Delete(context.Context, *v1alpha1.DeleteRequest) (*v1alpha1.DeleteResponse, error)
}

// NewEAMTServiceClient constructs a client for the siit.v1alpha1.EAMTService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEAMTServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EAMTServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eAMTServiceMethods := v1alpha1.File_siit_v1alpha1_siit_proto.Services().ByName("EAMTService").Methods()
	return &eAMTServiceClient{
		list: connect.NewClient[v1alpha1.ListRequest, v1alpha1.ListResponse](
			httpClient,
			baseURL+EAMTServiceListProcedure,
			connect.WithSchema(eAMTServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[v1alpha1.CreateRequest, v1alpha1.CreateResponse](
			httpClient,
			baseURL+EAMTServiceCreateProcedure,
			connect.WithSchema(eAMTServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1alpha1.DeleteRequest, v1alpha1.DeleteResponse](
			httpClient,
			baseURL+EAMTServiceDeleteProcedure,
			connect.WithSchema(eAMTServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eAMTServiceClient implements EAMTServiceClient.
type eAMTServiceClient struct {
	list   *connect.Client[v1alpha1.ListRequest, v1alpha1.ListResponse]
	create *connect.Client[v1alpha1.CreateRequest, v1alpha1.CreateResponse]
	delete *connect.Client[v1alpha1.DeleteRequest, v1alpha1.DeleteResponse]
}

// List calls siit.v1alpha1.EAMTService.List.
func (c *eAMTServiceClient) List(ctx context.Context, req *v1alpha1.ListRequest) (*v1alpha1.ListResponse, error) {
	response, err := c.list.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Create calls siit.v1alpha1.EAMTService.Create.
func (c *eAMTServiceClient) Create(ctx context.Context, req *v1alpha1.CreateRequest) (*v1alpha1.CreateResponse, error) {
	response, err := c.create.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// Delete calls siit.v1alpha1.EAMTService.Delete.
func (c *eAMTServiceClient) Delete(ctx context.Context, req *v1alpha1.DeleteRequest) (*v1alpha1.DeleteResponse, error) {
	response, err := c.delete.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EAMTServiceHandler is an implementation of the siit.v1alpha1.EAMTService service.
type EAMTServiceHandler interface {
	List(context.Context, *v1alpha1.ListRequest) (*v1alpha1.ListResponse, error)
	Create(context.Context, *v1alpha1.CreateRequest) (*v1alpha1.CreateResponse, error)
	Delete(context.Context, *v1alpha1.DeleteRequest) (*v1alpha1.DeleteResponse, error)
}

// NewEAMTServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEAMTServiceHandler(svc EAMTServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eAMTServiceMethods := v1alpha1.File_siit_v1alpha1_siit_proto.Services().ByName("EAMTService").Methods()
	eAMTServiceListHandler := connect.NewUnaryHandlerSimple(
		EAMTServiceListProcedure,
		svc.List,
		connect.WithSchema(eAMTServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	eAMTServiceCreateHandler := connect.NewUnaryHandlerSimple(
		EAMTServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(eAMTServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	eAMTServiceDeleteHandler := connect.NewUnaryHandlerSimple(
		EAMTServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(eAMTServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/siit.v1alpha1.EAMTService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EAMTServiceListProcedure:
			eAMTServiceListHandler.ServeHTTP(w, r)
		case EAMTServiceCreateProcedure:
			eAMTServiceCreateHandler.ServeHTTP(w, r)
		case EAMTServiceDeleteProcedure:
			eAMTServiceDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEAMTServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEAMTServiceHandler struct{}

func (UnimplementedEAMTServiceHandler) List(context.Context, *v1alpha1.ListRequest) (*v1alpha1.ListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("siit.v1alpha1.EAMTService.List is not implemented"))
}

func (UnimplementedEAMTServiceHandler) Create(context.Context, *v1alpha1.CreateRequest) (*v1alpha1.CreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("siit.v1alpha1.EAMTService.Create is not implemented"))
}

func (UnimplementedEAMTServiceHandler) Delete(context.Context, *v1alpha1.DeleteRequest) (*v1alpha1.DeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("siit.v1alpha1.EAMTService.Delete is not implemented"))
}
