package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"go/format"
	"io"
	"os"
	"strings"
	"unicode"

	"github.com/cilium/ebpf/btf"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "Error:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("expect location of compressed vmlinux .BTF as argument")
	}

	raw, err := ReadAllCompressed(args[0])
	if err != nil {
		return err
	}

	spec, err := btf.LoadSpecFromReader(bytes.NewReader(raw))
	if err != nil {
		return err
	}

	output, err := generateTypes(spec)
	if err != nil {
		return err
	}

	w, err := os.Create("types.go")
	if err != nil {
		return err
	}
	defer w.Close()

	formatted, err := format.Source(output)
	if err == nil {
		_, err = w.Write(formatted)
		return err
	}
	return err
}

func generateTypes(spec *btf.Spec) ([]byte, error) {
	w := bytes.NewBuffer(nil)
	w.WriteString(`// Code generated by testdata/gentypes; DO NOT EDIT.

package bpf

import (
	"structs"
)

`)

	objName := &btf.Array{Nelems: 16, Type: &btf.Int{Encoding: btf.Char, Size: 1}}
	linkID := &btf.Int{Size: 4}
	btfID := &btf.Int{Size: 4}
	typeID := &btf.Int{Size: 4}
	pointer := &btf.Int{Size: 8}
	logLevel := &btf.Int{Size: 4}
	mapFlags := &btf.Int{Size: 4}
	rawPointer := &btf.Pointer{}

	gf := &btf.GoFormatter{
		Names: map[btf.Type]string{
			objName:    "ObjName",
			linkID:     "LinkID",
			btfID:      "BTFID",
			typeID:     "TypeID",
			pointer:    "Pointer",
			logLevel:   "LogLevel",
			mapFlags:   "MapFlags",
			rawPointer: "Pointer",
		},
		Identifier: Identifier,
		EnumIdentifier: func(name, element string) string {
			return element
		},
	}
	structs := []struct {
		goType  string
		cType   string
		patches []patch
	}{
		{"skBuff", "__sk_buff", []patch{
			// remove anon union with pointer type
			name(26, "flow_keys"),
			remove("flow_keys"),
			name(29, "socket"),
			remove("socket"),
		}},
	}
	for _, s := range structs {
		fmt.Println("struct", s.goType)

		var t *btf.Struct
		if err := spec.TypeByName(s.cType, &t); err != nil {
			return nil, err
		}

		if err := outputPatchedStruct(gf, w, s.goType, t, s.patches); err != nil {
			return nil, fmt.Errorf("output %q: %w", s.goType, err)
		}
	}
	return w.Bytes(), nil
}

func outputPatchedStruct(gf *btf.GoFormatter, w *bytes.Buffer, id string, s *btf.Struct, patches []patch) error {
	s = btf.Copy(s).(*btf.Struct)

	for i, p := range patches {
		if err := p(s); err != nil {
			return fmt.Errorf("patch %d: %w", i, err)
		}
	}

	printBTFMembers(s.Name, s.Members)

	decl, err := gf.TypeDeclaration(id, s)
	if err != nil {
		return err
	}

	w.WriteString(decl)
	w.WriteString("\n\n")
	return nil
}

func ReadAllCompressed(file string) ([]byte, error) {
	fh, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer fh.Close()

	gz, err := gzip.NewReader(fh)
	if err != nil {
		return nil, err
	}
	defer gz.Close()

	return io.ReadAll(gz)
}

func printBTFMembers(parent string, members []btf.Member) {
	for i, mem := range members {
		fmt.Println("parent", parent, "index", i, "member", mem.Name, "type", mem.Type, "offset", mem.Offset)
		if u, ok := mem.Type.(*btf.Union); ok {
			printBTFMembers(u.Name, u.Members)
		}
	}
}

// Identifier turns a C style type or field name into an exportable Go equivalent.
// This is copied from the internal package in cilium/ebpf.
// https://github.com/cilium/ebpf/blob/d663e4e3c8f36d7253fac771876a513f70f72f70/internal/output.go#L15-L49
func Identifier(str string) string {
	prev := rune(-1)
	return strings.Map(func(r rune) rune {
		// See https://golang.org/ref/spec#Identifiers
		switch {
		case unicode.IsLetter(r):
			if prev == -1 {
				r = unicode.ToUpper(r)
			}

		case r == '_':
			switch {
			// The previous rune was deleted, or we are at the
			// beginning of the string.
			case prev == -1:
				fallthrough

			// The previous rune is a lower case letter or a digit.
			case unicode.IsDigit(prev) || (unicode.IsLetter(prev) && unicode.IsLower(prev)):
				// delete the current rune, and force the
				// next character to be uppercased.
				r = -1
			}

		case unicode.IsDigit(r):

		default:
			// Delete the current rune. prev is unchanged.
			return -1
		}

		prev = r
		return r
	}, str)
}
