// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type siitIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type siitInAddr struct {
	_      structs.HostLayout
	S_addr uint32
}

// loadSiit returns the embedded CollectionSpec for siit.
func loadSiit() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SiitBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load siit: %w", err)
	}

	return spec, err
}

// loadSiitObjects loads siit and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*siitObjects
//	*siitPrograms
//	*siitMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSiitObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSiit()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// siitSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siitSpecs struct {
	siitProgramSpecs
	siitMapSpecs
	siitVariableSpecs
}

// siitProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siitProgramSpecs struct {
	Siit *ebpf.ProgramSpec `ebpf:"siit"`
}

// siitMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siitMapSpecs struct {
	Ipv4AddressMappings *ebpf.MapSpec `ebpf:"ipv4_address_mappings"`
	Ipv6AddressMappings *ebpf.MapSpec `ebpf:"ipv6_address_mappings"`
}

// siitVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type siitVariableSpecs struct {
	IPV4IFINDEX *ebpf.VariableSpec `ebpf:"IPV4_IFINDEX"`
	IPV6IFINDEX *ebpf.VariableSpec `ebpf:"IPV6_IFINDEX"`
	IPV6POOL_0  *ebpf.VariableSpec `ebpf:"IPV6_POOL_0"`
	IPV6POOL_1  *ebpf.VariableSpec `ebpf:"IPV6_POOL_1"`
	IPV6POOL_2  *ebpf.VariableSpec `ebpf:"IPV6_POOL_2"`
}

// siitObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSiitObjects or ebpf.CollectionSpec.LoadAndAssign.
type siitObjects struct {
	siitPrograms
	siitMaps
	siitVariables
}

func (o *siitObjects) Close() error {
	return _SiitClose(
		&o.siitPrograms,
		&o.siitMaps,
	)
}

// siitMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSiitObjects or ebpf.CollectionSpec.LoadAndAssign.
type siitMaps struct {
	Ipv4AddressMappings *ebpf.Map `ebpf:"ipv4_address_mappings"`
	Ipv6AddressMappings *ebpf.Map `ebpf:"ipv6_address_mappings"`
}

func (m *siitMaps) Close() error {
	return _SiitClose(
		m.Ipv4AddressMappings,
		m.Ipv6AddressMappings,
	)
}

// siitVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSiitObjects or ebpf.CollectionSpec.LoadAndAssign.
type siitVariables struct {
	IPV4IFINDEX *ebpf.Variable `ebpf:"IPV4_IFINDEX"`
	IPV6IFINDEX *ebpf.Variable `ebpf:"IPV6_IFINDEX"`
	IPV6POOL_0  *ebpf.Variable `ebpf:"IPV6_POOL_0"`
	IPV6POOL_1  *ebpf.Variable `ebpf:"IPV6_POOL_1"`
	IPV6POOL_2  *ebpf.Variable `ebpf:"IPV6_POOL_2"`
}

// siitPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSiitObjects or ebpf.CollectionSpec.LoadAndAssign.
type siitPrograms struct {
	Siit *ebpf.Program `ebpf:"siit"`
}

func (p *siitPrograms) Close() error {
	return _SiitClose(
		p.Siit,
	)
}

func _SiitClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed siit_bpfeb.o
var _SiitBytes []byte
