// Code generated by testdata/gentypes; DO NOT EDIT.

package bpf

import (
	"structs"
)

type skBuff struct {
	_              structs.HostLayout
	Len            uint32
	PktType        uint32
	Mark           uint32
	QueueMapping   uint32
	Protocol       uint32
	VlanPresent    uint32
	VlanTci        uint32
	VlanProto      uint32
	Priority       uint32
	IngressIfindex uint32
	Ifindex        uint32
	TcIndex        uint32
	Cb             [5]uint32
	Hash           uint32
	TcClassid      uint32
	Data           uint32
	DataEnd        uint32
	NapiId         uint32
	Family         uint32
	RemoteIp4      uint32
	LocalIp4       uint32
	RemoteIp6      [4]uint32
	LocalIp6       [4]uint32
	RemotePort     uint32
	LocalPort      uint32
	DataMeta       uint32
	_              [8]byte
	Tstamp         uint64
	WireLen        uint32
	GsoSegs        uint32
	_              [8]byte
	GsoSize        uint32
	TstampType     uint8
	_              [3]byte
	Hwtstamp       uint64
}
