// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: siit/v1alpha1/siit.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *IPPrefix              `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetPool() *IPPrefix {
	if x != nil {
		return x.Pool
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EAMTEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetEntries() []*EAMTEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *IPPrefix              `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Entry         *EAMTEntry             `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetPool() *IPPrefix {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *CreateRequest) GetEntry() *EAMTEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *IPPrefix              `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Entry         *EAMTEntry             `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPool() *IPPrefix {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *DeleteRequest) GetEntry() *EAMTEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{5}
}

type EAMTEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          *IPAddress             `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          *IPAddress             `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EAMTEntry) Reset() {
	*x = EAMTEntry{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EAMTEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EAMTEntry) ProtoMessage() {}

func (x *EAMTEntry) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EAMTEntry.ProtoReflect.Descriptor instead.
func (*EAMTEntry) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{6}
}

func (x *EAMTEntry) GetIpv4() *IPAddress {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *EAMTEntry) GetIpv6() *IPAddress {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

type IPAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Ip:
	//
	//	*IPAddress_Ipv4
	//	*IPAddress_Ipv6
	Ip            isIPAddress_Ip `protobuf_oneof:"ip"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{7}
}

func (x *IPAddress) GetIp() isIPAddress_Ip {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *IPAddress) GetIpv4() string {
	if x != nil {
		if x, ok := x.Ip.(*IPAddress_Ipv4); ok {
			return x.Ipv4
		}
	}
	return ""
}

func (x *IPAddress) GetIpv6() string {
	if x != nil {
		if x, ok := x.Ip.(*IPAddress_Ipv6); ok {
			return x.Ipv6
		}
	}
	return ""
}

type isIPAddress_Ip interface {
	isIPAddress_Ip()
}

type IPAddress_Ipv4 struct {
	Ipv4 string `protobuf:"bytes,1,opt,name=ipv4,proto3,oneof"`
}

type IPAddress_Ipv6 struct {
	Ipv6 string `protobuf:"bytes,2,opt,name=ipv6,proto3,oneof"`
}

func (*IPAddress_Ipv4) isIPAddress_Ip() {}

func (*IPAddress_Ipv6) isIPAddress_Ip() {}

type IPPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *IPAddress             `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PrefixLen     uint32                 `protobuf:"varint,3,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPPrefix) Reset() {
	*x = IPPrefix{}
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPPrefix) ProtoMessage() {}

func (x *IPPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_siit_v1alpha1_siit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPPrefix.ProtoReflect.Descriptor instead.
func (*IPPrefix) Descriptor() ([]byte, []int) {
	return file_siit_v1alpha1_siit_proto_rawDescGZIP(), []int{8}
}

func (x *IPPrefix) GetIp() *IPAddress {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *IPPrefix) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

var File_siit_v1alpha1_siit_proto protoreflect.FileDescriptor

const file_siit_v1alpha1_siit_proto_rawDesc = "" +
	"\n" +
	"\x18siit/v1alpha1/siit.proto\x12\rsiit.v1alpha1\":\n" +
	"\vListRequest\x12+\n" +
	"\x04pool\x18\x01 \x01(\v2\x17.siit.v1alpha1.IPPrefixR\x04pool\"B\n" +
	"\fListResponse\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.siit.v1alpha1.EAMTEntryR\aentries\"l\n" +
	"\rCreateRequest\x12+\n" +
	"\x04pool\x18\x01 \x01(\v2\x17.siit.v1alpha1.IPPrefixR\x04pool\x12.\n" +
	"\x05entry\x18\x02 \x01(\v2\x18.siit.v1alpha1.EAMTEntryR\x05entry\"\x10\n" +
	"\x0eCreateResponse\"l\n" +
	"\rDeleteRequest\x12+\n" +
	"\x04pool\x18\x01 \x01(\v2\x17.siit.v1alpha1.IPPrefixR\x04pool\x12.\n" +
	"\x05entry\x18\x02 \x01(\v2\x18.siit.v1alpha1.EAMTEntryR\x05entry\"\x10\n" +
	"\x0eDeleteResponse\"g\n" +
	"\tEAMTEntry\x12,\n" +
	"\x04ipv4\x18\x01 \x01(\v2\x18.siit.v1alpha1.IPAddressR\x04ipv4\x12,\n" +
	"\x04ipv6\x18\x02 \x01(\v2\x18.siit.v1alpha1.IPAddressR\x04ipv6\"=\n" +
	"\tIPAddress\x12\x14\n" +
	"\x04ipv4\x18\x01 \x01(\tH\x00R\x04ipv4\x12\x14\n" +
	"\x04ipv6\x18\x02 \x01(\tH\x00R\x04ipv6B\x04\n" +
	"\x02ip\"S\n" +
	"\bIPPrefix\x12(\n" +
	"\x02ip\x18\x01 \x01(\v2\x18.siit.v1alpha1.IPAddressR\x02ip\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x03 \x01(\rR\tprefixLen2\xe2\x01\n" +
	"\vEAMTService\x12A\n" +
	"\x04List\x12\x1a.siit.v1alpha1.ListRequest\x1a\x1b.siit.v1alpha1.ListResponse\"\x00\x12G\n" +
	"\x06Create\x12\x1c.siit.v1alpha1.CreateRequest\x1a\x1d.siit.v1alpha1.CreateResponse\"\x00\x12G\n" +
	"\x06Delete\x12\x1c.siit.v1alpha1.DeleteRequest\x1a\x1d.siit.v1alpha1.DeleteResponse\"\x00B\xa7\x01\n" +
	"\x11com.siit.v1alpha1B\tSiitProtoP\x01Z2github.com/hown3d/siit-ebpf/pkg/apis/siit/v1alpha1\xa2\x02\x03SXX\xaa\x02\rSiit.V1alpha1\xca\x02\rSiit\\V1alpha1\xe2\x02\x19Siit\\V1alpha1\\GPBMetadata\xea\x02\x0eSiit::V1alpha1b\x06proto3"

var (
	file_siit_v1alpha1_siit_proto_rawDescOnce sync.Once
	file_siit_v1alpha1_siit_proto_rawDescData []byte
)

func file_siit_v1alpha1_siit_proto_rawDescGZIP() []byte {
	file_siit_v1alpha1_siit_proto_rawDescOnce.Do(func() {
		file_siit_v1alpha1_siit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_siit_v1alpha1_siit_proto_rawDesc), len(file_siit_v1alpha1_siit_proto_rawDesc)))
	})
	return file_siit_v1alpha1_siit_proto_rawDescData
}

var file_siit_v1alpha1_siit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_siit_v1alpha1_siit_proto_goTypes = []any{
	(*ListRequest)(nil),    // 0: siit.v1alpha1.ListRequest
	(*ListResponse)(nil),   // 1: siit.v1alpha1.ListResponse
	(*CreateRequest)(nil),  // 2: siit.v1alpha1.CreateRequest
	(*CreateResponse)(nil), // 3: siit.v1alpha1.CreateResponse
	(*DeleteRequest)(nil),  // 4: siit.v1alpha1.DeleteRequest
	(*DeleteResponse)(nil), // 5: siit.v1alpha1.DeleteResponse
	(*EAMTEntry)(nil),      // 6: siit.v1alpha1.EAMTEntry
	(*IPAddress)(nil),      // 7: siit.v1alpha1.IPAddress
	(*IPPrefix)(nil),       // 8: siit.v1alpha1.IPPrefix
}
var file_siit_v1alpha1_siit_proto_depIdxs = []int32{
	8,  // 0: siit.v1alpha1.ListRequest.pool:type_name -> siit.v1alpha1.IPPrefix
	6,  // 1: siit.v1alpha1.ListResponse.entries:type_name -> siit.v1alpha1.EAMTEntry
	8,  // 2: siit.v1alpha1.CreateRequest.pool:type_name -> siit.v1alpha1.IPPrefix
	6,  // 3: siit.v1alpha1.CreateRequest.entry:type_name -> siit.v1alpha1.EAMTEntry
	8,  // 4: siit.v1alpha1.DeleteRequest.pool:type_name -> siit.v1alpha1.IPPrefix
	6,  // 5: siit.v1alpha1.DeleteRequest.entry:type_name -> siit.v1alpha1.EAMTEntry
	7,  // 6: siit.v1alpha1.EAMTEntry.ipv4:type_name -> siit.v1alpha1.IPAddress
	7,  // 7: siit.v1alpha1.EAMTEntry.ipv6:type_name -> siit.v1alpha1.IPAddress
	7,  // 8: siit.v1alpha1.IPPrefix.ip:type_name -> siit.v1alpha1.IPAddress
	0,  // 9: siit.v1alpha1.EAMTService.List:input_type -> siit.v1alpha1.ListRequest
	2,  // 10: siit.v1alpha1.EAMTService.Create:input_type -> siit.v1alpha1.CreateRequest
	4,  // 11: siit.v1alpha1.EAMTService.Delete:input_type -> siit.v1alpha1.DeleteRequest
	1,  // 12: siit.v1alpha1.EAMTService.List:output_type -> siit.v1alpha1.ListResponse
	3,  // 13: siit.v1alpha1.EAMTService.Create:output_type -> siit.v1alpha1.CreateResponse
	5,  // 14: siit.v1alpha1.EAMTService.Delete:output_type -> siit.v1alpha1.DeleteResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_siit_v1alpha1_siit_proto_init() }
func file_siit_v1alpha1_siit_proto_init() {
	if File_siit_v1alpha1_siit_proto != nil {
		return
	}
	file_siit_v1alpha1_siit_proto_msgTypes[7].OneofWrappers = []any{
		(*IPAddress_Ipv4)(nil),
		(*IPAddress_Ipv6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_siit_v1alpha1_siit_proto_rawDesc), len(file_siit_v1alpha1_siit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_siit_v1alpha1_siit_proto_goTypes,
		DependencyIndexes: file_siit_v1alpha1_siit_proto_depIdxs,
		MessageInfos:      file_siit_v1alpha1_siit_proto_msgTypes,
	}.Build()
	File_siit_v1alpha1_siit_proto = out.File
	file_siit_v1alpha1_siit_proto_goTypes = nil
	file_siit_v1alpha1_siit_proto_depIdxs = nil
}
